-- =====================================================================
-- ASN — Admin user seed (Phase 3)
-- Run this AFTER 0002, 0003, 0004.
--
-- Pre-creates the founding admin team in `admin_users`. The `auth_user_id`
-- starts NULL and gets linked automatically the first time the admin
-- signs in with the 6-digit code (see /auth/callback in the app).
--
-- IMPORTANT — emails must match exactly what the admin will type at
-- /admin/login. They're case-insensitive (citext) so casing doesn't
-- matter, but typos do.
--
-- To add more admins later, do NOT edit this file: copy
-- supabase/seed.local.example.sql to supabase/seed.local.sql (gitignored),
-- fill in the rows, and run that in the SQL editor. This file is
-- idempotent (ON CONFLICT DO NOTHING), so re-running it is harmless.
-- =====================================================================

insert into public.admin_users (email, full_name, role, active)
values
  ('lester@ekwa.com',          'Lester',          'owner', true),
  ('rushdha@ekwa.com',         'Rushdha',         'admin', true),
  ('rushdhaakbar82@gmail.com', 'Rushdha (test)',  'admin', true),
  ('fathimarushdhaakbar28@gmail.com', 'Fathima Rushdha', 'admin', true)
on conflict (email) do nothing;

-- Confirm with:
--   select email, full_name, role, active, auth_user_id, last_active_at
--   from public.admin_users order by created_at;
